---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _layouts
  label: Layouts
  create: all
  match: "**/*"
- type: document
  path: Gemfile
  label: Gemfile
- type: document
  path: _config.yml
  label: Config
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
